name: ✨Feature request
description: Propone cosas nuevas para el proyecto.
labels: Feature-request
body:
- type: textarea
  attributes:
    label: Problema a resolver
  validations:
    required: true
- type: textarea
  attributes:
    label: Solucion propuesta.
    placeholder: Explicacions como solucionarias el problema
  validations:
    required: true
