name: Firebase Continuous Deployment

on:
  push:
    branches: [2.x]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: "Installing dependencies"
      - run: npm ci

      - name: "Building app"
      - run: npm run build

      - name: "Deploying to Firebase"
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
